export const FETCH_FOOD_ITEMS_REQUEST = "FETCH_FOOD_ITEMS_REQUEST";
export const FETCH_FOOD_ITEMS_SUCCESS = "FETCH_FOOD_ITEMS_SUCCESS";
export const FETCH_FOOD_ITEMS_FAILURE = "FETCH_FOOD_ITEMS_FAILURE";