export const FETCH_LIST_ITEMS_REQUEST = "FETCH_LIST_ITEMS_REQUEST";
export const FETCH_LIST_ITEMS_SUCCESS = "FETCH_LIST_ITEMS_SUCCESS";
export const FETCH_LIST_ITEMS_FAILURE = "FETCH_LIST_ITEMS_FAILURE";
